### ISSUE TITLE
Error when using Data

### ISSUE THREAD

**Issue by furesoft** [RyanLamansky/dotnet-webassembly#51] opened 2021-11-23 17:21 UTC
Hello,

I am adding the bytes of a string to a new Data Element. When I try to run the Code I get an Error: value.GetType(&elementType). The error code is E_NOTIMPL, or0x80004001.

It is so exhausting

**Comment by RyanLamansky** [comment] 2021-11-24 02:56
Can you provide more information to reproduce the issue?

**Comment by furesoft** [comment] 2021-11-24 12:13
`public static void AddData(this Module m, int address, byte[] raw)
    {
        m.Data.Add(new Data
        {
            Index = 0,
            InitializerExpression = new List<Instruction> {new Int32Constant(address), new End()},
            RawData = raw.ToList()
        });
    }`

when using this method I get the following WASM Binary: https://file.io/tcQTsNwUnU8v

The Error appears when I look into the Export Property of the created instance. If I run the wasm functions I get the following Error: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'void' to 'object'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)

**Comment by RyanLamansky** [comment] 2021-11-25 14:49
If I'm reading this right, the data is being copied to memory starting at offset 1024, but the imported memory limit is only 25. If the range check in WebAssembly for .NET isn't working (possible, I don't think it has any tests!), it could write outside of the memory and overwrite something important, causing weird errors like you're seeing.

Does this sound like it may be the problem? If this theory is correct, it could be fixed by making sure the WASM memory object is at least 1024 + raw.Length.

**Comment by furesoft** [comment] 2021-11-25 16:10
May this could be the problem but where does the 25 comes from?

**Comment by RyanLamansky** [comment] 2021-11-25 16:17
Oh, right--25 * 64kb page size should be plenty. It's been so long since I've worked on WASM that I've forgotten a few of the details 😅

I can look into this more this weekend when I'm back home from visiting relatives for Thanksgiving. My next theory is maybe it's not expanding the memory if it's initially too small to fit the data object.

**Comment by furesoft** [comment] 2021-11-25 16:18
OK thanks :D I hope this works soon. I can't work on this part in my project now, because I cannot test any function related to strings

**Comment by furesoft** [comment] 2021-11-25 16:29
I have tried to use the address 0 for the string but same behavior

**Comment by RyanLamansky** [comment] 2021-11-25 16:34
One of the things I did a couple years ago was convert the official WASM spec tests to something usable by this library. It has data tests, and they mostly pass. Some edge cases are currently skipped but none result in the error you're seeing.

I wonder if the problem may be with how you're accessing the object using `dynamic`. "RuntimeBinderException: Cannot implicitly convert type 'void' to 'object'" suggests the return type of what you're accessing is now what you expect.

Can you share the code for how you're accessing it?

**Comment by furesoft** [comment] 2021-11-25 16:48
dynamic has already worked. And If I remove the data it works again. So the problem is definitly at the data part

`

        var compiled = m.Compile<dynamic>();
        var instance = compiled(imports);

        ModuleEventStorage.SubscribeModule(instance.Exports);

        return instance.Exports;
`

**Comment by RyanLamansky** [comment] 2021-11-25 17:43
Can you create a minimal example that reproduces the issue? The less code, steps, and dependencies the better.

**Comment by furesoft** [comment] 2021-11-25 17:53
Here a really simple wasm module: https://file.io/tvdOiUMvqXhx

`

        var m = Module.ReadFromBinary("../testScript.wasm");
        var r = m.Compile<dynamic>();
        var rr = r(new ImportDictionary
        {
            ["env"] = new Dictionary<string, RuntimeImport>
            {
                ["memory"] = new MemoryImport(() => new UnmanagedMemory(1, 2))
            }
        });
`

**Comment by furesoft** [comment] 2021-11-28 08:39
Any updates?

**Comment by RyanLamansky** [comment] 2021-11-28 14:36
The issue isn't reproducing for me.

I added the WASM linked in your most recent message and used your code to build a test, but the test is passing.

You can see the test code here: https://github.com/RyanLamansky/dotnet-webassembly/blob/issue51/WebAssembly.Tests/SampleTests.cs#L82

Can you tell me how to change the test to trigger the problem? You can also fork the project and edit it yourself.

**Comment by furesoft** [comment] 2021-11-28 15:05
hmm. I use your test with my wasm file. I get a "System.IO.EndOfStreamException" in System.Private.CoreLib.dll

**Comment by furesoft** [comment] 2021-11-28 15:29
lol. it does work now. But I don't know why

**Closed as completed** 2021-12-05 15:54 UTC
Labels: Troubleshooting
